namespace QuanLyCuaHangThoiTrangKD.Forms.Function
{
    partial class FormDanhsachHangchoHoadon
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormDanhsachHangchoHoadon));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.grdDanhsachHDHangcho = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.Mahd = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TenKH = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.SDT = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.bunifuShapes1 = new Bunifu.UI.WinForms.BunifuShapes();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.btnDong = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.txtSDTKH = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnThanhtoanHDHangcho = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoaHDHangcho = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTImkiemHDHangcho = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoaTatcaHDHangcho = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtSotrang = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnLast = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFirst = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPrev = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.grdDanhsachHDHangcho)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // grdDanhsachHDHangcho
            // 
            this.grdDanhsachHDHangcho.AllowCustomTheming = false;
            this.grdDanhsachHDHangcho.AllowUserToAddRows = false;
            this.grdDanhsachHDHangcho.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.grdDanhsachHDHangcho.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.grdDanhsachHDHangcho.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.grdDanhsachHDHangcho.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.grdDanhsachHDHangcho.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.grdDanhsachHDHangcho.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.grdDanhsachHDHangcho.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.grdDanhsachHDHangcho.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.grdDanhsachHDHangcho.ColumnHeadersHeight = 40;
            this.grdDanhsachHDHangcho.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Mahd,
            this.TenKH,
            this.SDT});
            this.grdDanhsachHDHangcho.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.grdDanhsachHDHangcho.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.grdDanhsachHDHangcho.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grdDanhsachHDHangcho.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.grdDanhsachHDHangcho.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.grdDanhsachHDHangcho.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.grdDanhsachHDHangcho.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.grdDanhsachHDHangcho.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.grdDanhsachHDHangcho.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.grdDanhsachHDHangcho.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.grdDanhsachHDHangcho.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.grdDanhsachHDHangcho.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.grdDanhsachHDHangcho.CurrentTheme.Name = null;
            this.grdDanhsachHDHangcho.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.grdDanhsachHDHangcho.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.grdDanhsachHDHangcho.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grdDanhsachHDHangcho.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.grdDanhsachHDHangcho.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.grdDanhsachHDHangcho.DefaultCellStyle = dataGridViewCellStyle3;
            this.grdDanhsachHDHangcho.EnableHeadersVisualStyles = false;
            this.grdDanhsachHDHangcho.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.grdDanhsachHDHangcho.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.grdDanhsachHDHangcho.HeaderBgColor = System.Drawing.Color.Empty;
            this.grdDanhsachHDHangcho.HeaderForeColor = System.Drawing.Color.White;
            this.grdDanhsachHDHangcho.Location = new System.Drawing.Point(31, 192);
            this.grdDanhsachHDHangcho.MultiSelect = false;
            this.grdDanhsachHDHangcho.Name = "grdDanhsachHDHangcho";
            this.grdDanhsachHDHangcho.ReadOnly = true;
            this.grdDanhsachHDHangcho.RowHeadersVisible = false;
            this.grdDanhsachHDHangcho.RowHeadersWidth = 50;
            this.grdDanhsachHDHangcho.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.grdDanhsachHDHangcho.RowTemplate.Height = 40;
            this.grdDanhsachHDHangcho.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.grdDanhsachHDHangcho.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grdDanhsachHDHangcho.Size = new System.Drawing.Size(778, 477);
            this.grdDanhsachHDHangcho.TabIndex = 112;
            this.grdDanhsachHDHangcho.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Mahd
            // 
            this.Mahd.HeaderText = "Mã hóa đơn";
            this.Mahd.Name = "Mahd";
            this.Mahd.ReadOnly = true;
            // 
            // TenKH
            // 
            this.TenKH.FillWeight = 140F;
            this.TenKH.HeaderText = "Tên khách hàng";
            this.TenKH.Name = "TenKH";
            this.TenKH.ReadOnly = true;
            // 
            // SDT
            // 
            this.SDT.FillWeight = 80F;
            this.SDT.HeaderText = "Số điện thoại";
            this.SDT.Name = "SDT";
            this.SDT.ReadOnly = true;
            // 
            // bunifuShapes1
            // 
            this.bunifuShapes1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuShapes1.Angle = 0F;
            this.bunifuShapes1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuShapes1.BorderThickness = 2;
            this.bunifuShapes1.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.FillShape = true;
            this.bunifuShapes1.Location = new System.Drawing.Point(31, 162);
            this.bunifuShapes1.Name = "bunifuShapes1";
            this.bunifuShapes1.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes1.Sides = 5;
            this.bunifuShapes1.Size = new System.Drawing.Size(520, 11);
            this.bunifuShapes1.TabIndex = 121;
            this.bunifuShapes1.Text = "bunifuShapes1";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(29, 122);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(177, 35);
            this.label2.TabIndex = 120;
            this.label2.Text = "Số điện thoại:";
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.btnDong);
            this.bunifuGradientPanel1.Controls.Add(this.label1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.Gray;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(11)))), ((int)(((byte)(7)))), ((int)(((byte)(17)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.Gray;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1085, 70);
            this.bunifuGradientPanel1.TabIndex = 122;
            // 
            // btnDong
            // 
            this.btnDong.AllowAnimations = true;
            this.btnDong.AllowMouseEffects = true;
            this.btnDong.AllowToggling = false;
            this.btnDong.AnimationSpeed = 200;
            this.btnDong.AutoGenerateColors = false;
            this.btnDong.AutoRoundBorders = false;
            this.btnDong.AutoSizeLeftIcon = true;
            this.btnDong.AutoSizeRightIcon = true;
            this.btnDong.BackColor = System.Drawing.Color.Transparent;
            this.btnDong.BackColor1 = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDong.BackgroundImage")));
            this.btnDong.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.ButtonText = "";
            this.btnDong.ButtonTextMarginLeft = 0;
            this.btnDong.ColorContrastOnClick = 45;
            this.btnDong.ColorContrastOnHover = 45;
            this.btnDong.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDong.CustomizableEdges = borderEdges1;
            this.btnDong.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDong.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDong.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDong.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDong.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnDong.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDong.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDong.ForeColor = System.Drawing.Color.White;
            this.btnDong.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDong.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDong.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDong.IconMarginLeft = 11;
            this.btnDong.IconPadding = 10;
            this.btnDong.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDong.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDong.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDong.IconSize = 25;
            this.btnDong.IdleBorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.IdleBorderRadius = 1;
            this.btnDong.IdleBorderThickness = 1;
            this.btnDong.IdleFillColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.IdleIconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.x;
            this.btnDong.IdleIconRightImage = null;
            this.btnDong.IndicateFocus = false;
            this.btnDong.Location = new System.Drawing.Point(0, 0);
            this.btnDong.Name = "btnDong";
            this.btnDong.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDong.OnDisabledState.BorderRadius = 1;
            this.btnDong.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnDisabledState.BorderThickness = 1;
            this.btnDong.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDong.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDong.OnDisabledState.IconLeftImage = null;
            this.btnDong.OnDisabledState.IconRightImage = null;
            this.btnDong.onHoverState.BorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.onHoverState.BorderRadius = 1;
            this.btnDong.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.onHoverState.BorderThickness = 1;
            this.btnDong.onHoverState.FillColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDong.onHoverState.IconLeftImage = null;
            this.btnDong.onHoverState.IconRightImage = null;
            this.btnDong.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.OnIdleState.BorderRadius = 1;
            this.btnDong.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnIdleState.BorderThickness = 1;
            this.btnDong.OnIdleState.FillColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDong.OnIdleState.IconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.x;
            this.btnDong.OnIdleState.IconRightImage = null;
            this.btnDong.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.OnPressedState.BorderRadius = 1;
            this.btnDong.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDong.OnPressedState.BorderThickness = 1;
            this.btnDong.OnPressedState.FillColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnDong.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDong.OnPressedState.IconLeftImage = null;
            this.btnDong.OnPressedState.IconRightImage = null;
            this.btnDong.Size = new System.Drawing.Size(77, 70);
            this.btnDong.TabIndex = 1;
            this.btnDong.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDong.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDong.TextMarginLeft = 0;
            this.btnDong.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDong.UseDefaultRadiusAndThickness = true;
            this.btnDong.Click += new System.EventHandler(this.btnDong_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 19F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(212, 20);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(700, 37);
            this.label1.TabIndex = 111;
            this.label1.Text = "DANH SÁCH HÓA ĐƠN CHỜ THANH TOÁN";
            // 
            // txtSDTKH
            // 
            this.txtSDTKH.AcceptsReturn = false;
            this.txtSDTKH.AcceptsTab = false;
            this.txtSDTKH.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSDTKH.AnimationSpeed = 200;
            this.txtSDTKH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSDTKH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSDTKH.BackColor = System.Drawing.Color.Transparent;
            this.txtSDTKH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSDTKH.BackgroundImage")));
            this.txtSDTKH.BorderColorActive = System.Drawing.Color.Gainsboro;
            this.txtSDTKH.BorderColorDisabled = System.Drawing.Color.Gainsboro;
            this.txtSDTKH.BorderColorHover = System.Drawing.Color.Gainsboro;
            this.txtSDTKH.BorderColorIdle = System.Drawing.Color.Gainsboro;
            this.txtSDTKH.BorderRadius = 1;
            this.txtSDTKH.BorderThickness = 1;
            this.txtSDTKH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSDTKH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDTKH.DefaultFont = new System.Drawing.Font("Segoe UI", 15F);
            this.txtSDTKH.DefaultText = "";
            this.txtSDTKH.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSDTKH.HideSelection = true;
            this.txtSDTKH.IconLeft = null;
            this.txtSDTKH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDTKH.IconPadding = 10;
            this.txtSDTKH.IconRight = null;
            this.txtSDTKH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDTKH.Lines = new string[0];
            this.txtSDTKH.Location = new System.Drawing.Point(249, 111);
            this.txtSDTKH.MaxLength = 32767;
            this.txtSDTKH.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSDTKH.Modified = false;
            this.txtSDTKH.Multiline = false;
            this.txtSDTKH.Name = "txtSDTKH";
            stateProperties1.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDTKH.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSDTKH.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDTKH.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Gainsboro;
            stateProperties4.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDTKH.OnIdleState = stateProperties4;
            this.txtSDTKH.Padding = new System.Windows.Forms.Padding(3);
            this.txtSDTKH.PasswordChar = '\0';
            this.txtSDTKH.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txtSDTKH.PlaceholderText = "Nhập số điện thoại";
            this.txtSDTKH.ReadOnly = false;
            this.txtSDTKH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSDTKH.SelectedText = "";
            this.txtSDTKH.SelectionLength = 0;
            this.txtSDTKH.SelectionStart = 0;
            this.txtSDTKH.ShortcutsEnabled = true;
            this.txtSDTKH.Size = new System.Drawing.Size(302, 54);
            this.txtSDTKH.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSDTKH.TabIndex = 119;
            this.txtSDTKH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSDTKH.TextMarginBottom = 0;
            this.txtSDTKH.TextMarginLeft = 3;
            this.txtSDTKH.TextMarginTop = 0;
            this.txtSDTKH.TextPlaceholder = "Nhập số điện thoại";
            this.txtSDTKH.UseSystemPasswordChar = false;
            this.txtSDTKH.WordWrap = true;
            // 
            // btnThanhtoanHDHangcho
            // 
            this.btnThanhtoanHDHangcho.AllowAnimations = true;
            this.btnThanhtoanHDHangcho.AllowMouseEffects = true;
            this.btnThanhtoanHDHangcho.AllowToggling = false;
            this.btnThanhtoanHDHangcho.AnimationSpeed = 200;
            this.btnThanhtoanHDHangcho.AutoGenerateColors = false;
            this.btnThanhtoanHDHangcho.AutoRoundBorders = false;
            this.btnThanhtoanHDHangcho.AutoSizeLeftIcon = true;
            this.btnThanhtoanHDHangcho.AutoSizeRightIcon = true;
            this.btnThanhtoanHDHangcho.BackColor = System.Drawing.Color.Transparent;
            this.btnThanhtoanHDHangcho.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnThanhtoanHDHangcho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThanhtoanHDHangcho.BackgroundImage")));
            this.btnThanhtoanHDHangcho.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThanhtoanHDHangcho.ButtonText = "Thanh toán (F4)";
            this.btnThanhtoanHDHangcho.ButtonTextMarginLeft = 0;
            this.btnThanhtoanHDHangcho.ColorContrastOnClick = 45;
            this.btnThanhtoanHDHangcho.ColorContrastOnHover = 45;
            this.btnThanhtoanHDHangcho.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnThanhtoanHDHangcho.CustomizableEdges = borderEdges2;
            this.btnThanhtoanHDHangcho.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThanhtoanHDHangcho.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThanhtoanHDHangcho.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThanhtoanHDHangcho.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThanhtoanHDHangcho.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThanhtoanHDHangcho.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.btnThanhtoanHDHangcho.ForeColor = System.Drawing.Color.White;
            this.btnThanhtoanHDHangcho.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThanhtoanHDHangcho.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThanhtoanHDHangcho.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThanhtoanHDHangcho.IconMarginLeft = 11;
            this.btnThanhtoanHDHangcho.IconPadding = 10;
            this.btnThanhtoanHDHangcho.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThanhtoanHDHangcho.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThanhtoanHDHangcho.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThanhtoanHDHangcho.IconSize = 25;
            this.btnThanhtoanHDHangcho.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThanhtoanHDHangcho.IdleBorderRadius = 30;
            this.btnThanhtoanHDHangcho.IdleBorderThickness = 1;
            this.btnThanhtoanHDHangcho.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnThanhtoanHDHangcho.IdleIconLeftImage = null;
            this.btnThanhtoanHDHangcho.IdleIconRightImage = null;
            this.btnThanhtoanHDHangcho.IndicateFocus = false;
            this.btnThanhtoanHDHangcho.Location = new System.Drawing.Point(826, 619);
            this.btnThanhtoanHDHangcho.Name = "btnThanhtoanHDHangcho";
            this.btnThanhtoanHDHangcho.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThanhtoanHDHangcho.OnDisabledState.BorderRadius = 30;
            this.btnThanhtoanHDHangcho.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThanhtoanHDHangcho.OnDisabledState.BorderThickness = 1;
            this.btnThanhtoanHDHangcho.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThanhtoanHDHangcho.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThanhtoanHDHangcho.OnDisabledState.IconLeftImage = null;
            this.btnThanhtoanHDHangcho.OnDisabledState.IconRightImage = null;
            this.btnThanhtoanHDHangcho.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnThanhtoanHDHangcho.onHoverState.BorderRadius = 30;
            this.btnThanhtoanHDHangcho.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThanhtoanHDHangcho.onHoverState.BorderThickness = 1;
            this.btnThanhtoanHDHangcho.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.btnThanhtoanHDHangcho.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThanhtoanHDHangcho.onHoverState.IconLeftImage = null;
            this.btnThanhtoanHDHangcho.onHoverState.IconRightImage = null;
            this.btnThanhtoanHDHangcho.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThanhtoanHDHangcho.OnIdleState.BorderRadius = 30;
            this.btnThanhtoanHDHangcho.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThanhtoanHDHangcho.OnIdleState.BorderThickness = 1;
            this.btnThanhtoanHDHangcho.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThanhtoanHDHangcho.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThanhtoanHDHangcho.OnIdleState.IconLeftImage = null;
            this.btnThanhtoanHDHangcho.OnIdleState.IconRightImage = null;
            this.btnThanhtoanHDHangcho.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThanhtoanHDHangcho.OnPressedState.BorderRadius = 30;
            this.btnThanhtoanHDHangcho.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThanhtoanHDHangcho.OnPressedState.BorderThickness = 1;
            this.btnThanhtoanHDHangcho.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThanhtoanHDHangcho.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThanhtoanHDHangcho.OnPressedState.IconLeftImage = null;
            this.btnThanhtoanHDHangcho.OnPressedState.IconRightImage = null;
            this.btnThanhtoanHDHangcho.Size = new System.Drawing.Size(228, 50);
            this.btnThanhtoanHDHangcho.TabIndex = 118;
            this.btnThanhtoanHDHangcho.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThanhtoanHDHangcho.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThanhtoanHDHangcho.TextMarginLeft = 0;
            this.btnThanhtoanHDHangcho.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThanhtoanHDHangcho.UseDefaultRadiusAndThickness = true;
            this.btnThanhtoanHDHangcho.Click += new System.EventHandler(this.btnThanhtoanHDHangcho_Click);
            // 
            // btnXoaHDHangcho
            // 
            this.btnXoaHDHangcho.AllowAnimations = true;
            this.btnXoaHDHangcho.AllowMouseEffects = true;
            this.btnXoaHDHangcho.AllowToggling = false;
            this.btnXoaHDHangcho.AnimationSpeed = 200;
            this.btnXoaHDHangcho.AutoGenerateColors = false;
            this.btnXoaHDHangcho.AutoRoundBorders = false;
            this.btnXoaHDHangcho.AutoSizeLeftIcon = true;
            this.btnXoaHDHangcho.AutoSizeRightIcon = true;
            this.btnXoaHDHangcho.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaHDHangcho.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnXoaHDHangcho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaHDHangcho.BackgroundImage")));
            this.btnXoaHDHangcho.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaHDHangcho.ButtonText = "Xóa (F3)";
            this.btnXoaHDHangcho.ButtonTextMarginLeft = 0;
            this.btnXoaHDHangcho.ColorContrastOnClick = 45;
            this.btnXoaHDHangcho.ColorContrastOnHover = 45;
            this.btnXoaHDHangcho.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnXoaHDHangcho.CustomizableEdges = borderEdges3;
            this.btnXoaHDHangcho.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaHDHangcho.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaHDHangcho.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaHDHangcho.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaHDHangcho.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaHDHangcho.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.btnXoaHDHangcho.ForeColor = System.Drawing.Color.White;
            this.btnXoaHDHangcho.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoaHDHangcho.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaHDHangcho.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoaHDHangcho.IconMarginLeft = 11;
            this.btnXoaHDHangcho.IconPadding = 10;
            this.btnXoaHDHangcho.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoaHDHangcho.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaHDHangcho.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoaHDHangcho.IconSize = 25;
            this.btnXoaHDHangcho.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaHDHangcho.IdleBorderRadius = 30;
            this.btnXoaHDHangcho.IdleBorderThickness = 1;
            this.btnXoaHDHangcho.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaHDHangcho.IdleIconLeftImage = null;
            this.btnXoaHDHangcho.IdleIconRightImage = null;
            this.btnXoaHDHangcho.IndicateFocus = false;
            this.btnXoaHDHangcho.Location = new System.Drawing.Point(826, 259);
            this.btnXoaHDHangcho.Name = "btnXoaHDHangcho";
            this.btnXoaHDHangcho.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaHDHangcho.OnDisabledState.BorderRadius = 30;
            this.btnXoaHDHangcho.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaHDHangcho.OnDisabledState.BorderThickness = 1;
            this.btnXoaHDHangcho.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaHDHangcho.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaHDHangcho.OnDisabledState.IconLeftImage = null;
            this.btnXoaHDHangcho.OnDisabledState.IconRightImage = null;
            this.btnXoaHDHangcho.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnXoaHDHangcho.onHoverState.BorderRadius = 30;
            this.btnXoaHDHangcho.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaHDHangcho.onHoverState.BorderThickness = 1;
            this.btnXoaHDHangcho.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.btnXoaHDHangcho.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoaHDHangcho.onHoverState.IconLeftImage = null;
            this.btnXoaHDHangcho.onHoverState.IconRightImage = null;
            this.btnXoaHDHangcho.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaHDHangcho.OnIdleState.BorderRadius = 30;
            this.btnXoaHDHangcho.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaHDHangcho.OnIdleState.BorderThickness = 1;
            this.btnXoaHDHangcho.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaHDHangcho.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoaHDHangcho.OnIdleState.IconLeftImage = null;
            this.btnXoaHDHangcho.OnIdleState.IconRightImage = null;
            this.btnXoaHDHangcho.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaHDHangcho.OnPressedState.BorderRadius = 30;
            this.btnXoaHDHangcho.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaHDHangcho.OnPressedState.BorderThickness = 1;
            this.btnXoaHDHangcho.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaHDHangcho.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoaHDHangcho.OnPressedState.IconLeftImage = null;
            this.btnXoaHDHangcho.OnPressedState.IconRightImage = null;
            this.btnXoaHDHangcho.Size = new System.Drawing.Size(228, 50);
            this.btnXoaHDHangcho.TabIndex = 118;
            this.btnXoaHDHangcho.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaHDHangcho.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoaHDHangcho.TextMarginLeft = 0;
            this.btnXoaHDHangcho.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoaHDHangcho.UseDefaultRadiusAndThickness = true;
            this.btnXoaHDHangcho.Click += new System.EventHandler(this.btnXoaHDHangcho_Click);
            // 
            // btnTImkiemHDHangcho
            // 
            this.btnTImkiemHDHangcho.AllowAnimations = true;
            this.btnTImkiemHDHangcho.AllowMouseEffects = true;
            this.btnTImkiemHDHangcho.AllowToggling = false;
            this.btnTImkiemHDHangcho.AnimationSpeed = 200;
            this.btnTImkiemHDHangcho.AutoGenerateColors = false;
            this.btnTImkiemHDHangcho.AutoRoundBorders = false;
            this.btnTImkiemHDHangcho.AutoSizeLeftIcon = true;
            this.btnTImkiemHDHangcho.AutoSizeRightIcon = true;
            this.btnTImkiemHDHangcho.BackColor = System.Drawing.Color.Transparent;
            this.btnTImkiemHDHangcho.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnTImkiemHDHangcho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTImkiemHDHangcho.BackgroundImage")));
            this.btnTImkiemHDHangcho.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTImkiemHDHangcho.ButtonText = "Tìm kiếm (F1)";
            this.btnTImkiemHDHangcho.ButtonTextMarginLeft = 0;
            this.btnTImkiemHDHangcho.ColorContrastOnClick = 45;
            this.btnTImkiemHDHangcho.ColorContrastOnHover = 45;
            this.btnTImkiemHDHangcho.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnTImkiemHDHangcho.CustomizableEdges = borderEdges4;
            this.btnTImkiemHDHangcho.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTImkiemHDHangcho.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTImkiemHDHangcho.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTImkiemHDHangcho.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTImkiemHDHangcho.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTImkiemHDHangcho.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.btnTImkiemHDHangcho.ForeColor = System.Drawing.Color.White;
            this.btnTImkiemHDHangcho.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTImkiemHDHangcho.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTImkiemHDHangcho.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTImkiemHDHangcho.IconMarginLeft = 11;
            this.btnTImkiemHDHangcho.IconPadding = 10;
            this.btnTImkiemHDHangcho.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTImkiemHDHangcho.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTImkiemHDHangcho.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTImkiemHDHangcho.IconSize = 25;
            this.btnTImkiemHDHangcho.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTImkiemHDHangcho.IdleBorderRadius = 30;
            this.btnTImkiemHDHangcho.IdleBorderThickness = 1;
            this.btnTImkiemHDHangcho.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnTImkiemHDHangcho.IdleIconLeftImage = null;
            this.btnTImkiemHDHangcho.IdleIconRightImage = null;
            this.btnTImkiemHDHangcho.IndicateFocus = false;
            this.btnTImkiemHDHangcho.Location = new System.Drawing.Point(571, 122);
            this.btnTImkiemHDHangcho.Name = "btnTImkiemHDHangcho";
            this.btnTImkiemHDHangcho.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTImkiemHDHangcho.OnDisabledState.BorderRadius = 30;
            this.btnTImkiemHDHangcho.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTImkiemHDHangcho.OnDisabledState.BorderThickness = 1;
            this.btnTImkiemHDHangcho.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTImkiemHDHangcho.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTImkiemHDHangcho.OnDisabledState.IconLeftImage = null;
            this.btnTImkiemHDHangcho.OnDisabledState.IconRightImage = null;
            this.btnTImkiemHDHangcho.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnTImkiemHDHangcho.onHoverState.BorderRadius = 30;
            this.btnTImkiemHDHangcho.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTImkiemHDHangcho.onHoverState.BorderThickness = 1;
            this.btnTImkiemHDHangcho.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.btnTImkiemHDHangcho.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTImkiemHDHangcho.onHoverState.IconLeftImage = null;
            this.btnTImkiemHDHangcho.onHoverState.IconRightImage = null;
            this.btnTImkiemHDHangcho.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTImkiemHDHangcho.OnIdleState.BorderRadius = 30;
            this.btnTImkiemHDHangcho.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTImkiemHDHangcho.OnIdleState.BorderThickness = 1;
            this.btnTImkiemHDHangcho.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnTImkiemHDHangcho.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTImkiemHDHangcho.OnIdleState.IconLeftImage = null;
            this.btnTImkiemHDHangcho.OnIdleState.IconRightImage = null;
            this.btnTImkiemHDHangcho.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTImkiemHDHangcho.OnPressedState.BorderRadius = 30;
            this.btnTImkiemHDHangcho.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTImkiemHDHangcho.OnPressedState.BorderThickness = 1;
            this.btnTImkiemHDHangcho.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTImkiemHDHangcho.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTImkiemHDHangcho.OnPressedState.IconLeftImage = null;
            this.btnTImkiemHDHangcho.OnPressedState.IconRightImage = null;
            this.btnTImkiemHDHangcho.Size = new System.Drawing.Size(238, 50);
            this.btnTImkiemHDHangcho.TabIndex = 118;
            this.btnTImkiemHDHangcho.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTImkiemHDHangcho.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTImkiemHDHangcho.TextMarginLeft = 0;
            this.btnTImkiemHDHangcho.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTImkiemHDHangcho.UseDefaultRadiusAndThickness = true;
            this.btnTImkiemHDHangcho.Click += new System.EventHandler(this.btnTImkiemHDHangcho_Click);
            // 
            // btnXoaTatcaHDHangcho
            // 
            this.btnXoaTatcaHDHangcho.AllowAnimations = true;
            this.btnXoaTatcaHDHangcho.AllowMouseEffects = true;
            this.btnXoaTatcaHDHangcho.AllowToggling = false;
            this.btnXoaTatcaHDHangcho.AnimationSpeed = 200;
            this.btnXoaTatcaHDHangcho.AutoGenerateColors = false;
            this.btnXoaTatcaHDHangcho.AutoRoundBorders = false;
            this.btnXoaTatcaHDHangcho.AutoSizeLeftIcon = true;
            this.btnXoaTatcaHDHangcho.AutoSizeRightIcon = true;
            this.btnXoaTatcaHDHangcho.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaTatcaHDHangcho.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnXoaTatcaHDHangcho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaTatcaHDHangcho.BackgroundImage")));
            this.btnXoaTatcaHDHangcho.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaTatcaHDHangcho.ButtonText = "Xóa tất cả (F2)";
            this.btnXoaTatcaHDHangcho.ButtonTextMarginLeft = 0;
            this.btnXoaTatcaHDHangcho.ColorContrastOnClick = 45;
            this.btnXoaTatcaHDHangcho.ColorContrastOnHover = 45;
            this.btnXoaTatcaHDHangcho.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnXoaTatcaHDHangcho.CustomizableEdges = borderEdges5;
            this.btnXoaTatcaHDHangcho.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaTatcaHDHangcho.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaTatcaHDHangcho.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaTatcaHDHangcho.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaTatcaHDHangcho.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaTatcaHDHangcho.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.btnXoaTatcaHDHangcho.ForeColor = System.Drawing.Color.White;
            this.btnXoaTatcaHDHangcho.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoaTatcaHDHangcho.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaTatcaHDHangcho.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoaTatcaHDHangcho.IconMarginLeft = 11;
            this.btnXoaTatcaHDHangcho.IconPadding = 10;
            this.btnXoaTatcaHDHangcho.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoaTatcaHDHangcho.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaTatcaHDHangcho.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoaTatcaHDHangcho.IconSize = 25;
            this.btnXoaTatcaHDHangcho.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaTatcaHDHangcho.IdleBorderRadius = 30;
            this.btnXoaTatcaHDHangcho.IdleBorderThickness = 1;
            this.btnXoaTatcaHDHangcho.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaTatcaHDHangcho.IdleIconLeftImage = null;
            this.btnXoaTatcaHDHangcho.IdleIconRightImage = null;
            this.btnXoaTatcaHDHangcho.IndicateFocus = false;
            this.btnXoaTatcaHDHangcho.Location = new System.Drawing.Point(826, 192);
            this.btnXoaTatcaHDHangcho.Name = "btnXoaTatcaHDHangcho";
            this.btnXoaTatcaHDHangcho.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaTatcaHDHangcho.OnDisabledState.BorderRadius = 30;
            this.btnXoaTatcaHDHangcho.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaTatcaHDHangcho.OnDisabledState.BorderThickness = 1;
            this.btnXoaTatcaHDHangcho.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaTatcaHDHangcho.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaTatcaHDHangcho.OnDisabledState.IconLeftImage = null;
            this.btnXoaTatcaHDHangcho.OnDisabledState.IconRightImage = null;
            this.btnXoaTatcaHDHangcho.onHoverState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnXoaTatcaHDHangcho.onHoverState.BorderRadius = 30;
            this.btnXoaTatcaHDHangcho.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaTatcaHDHangcho.onHoverState.BorderThickness = 1;
            this.btnXoaTatcaHDHangcho.onHoverState.FillColor = System.Drawing.Color.DarkGray;
            this.btnXoaTatcaHDHangcho.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoaTatcaHDHangcho.onHoverState.IconLeftImage = null;
            this.btnXoaTatcaHDHangcho.onHoverState.IconRightImage = null;
            this.btnXoaTatcaHDHangcho.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaTatcaHDHangcho.OnIdleState.BorderRadius = 30;
            this.btnXoaTatcaHDHangcho.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaTatcaHDHangcho.OnIdleState.BorderThickness = 1;
            this.btnXoaTatcaHDHangcho.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnXoaTatcaHDHangcho.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoaTatcaHDHangcho.OnIdleState.IconLeftImage = null;
            this.btnXoaTatcaHDHangcho.OnIdleState.IconRightImage = null;
            this.btnXoaTatcaHDHangcho.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaTatcaHDHangcho.OnPressedState.BorderRadius = 30;
            this.btnXoaTatcaHDHangcho.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaTatcaHDHangcho.OnPressedState.BorderThickness = 1;
            this.btnXoaTatcaHDHangcho.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaTatcaHDHangcho.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoaTatcaHDHangcho.OnPressedState.IconLeftImage = null;
            this.btnXoaTatcaHDHangcho.OnPressedState.IconRightImage = null;
            this.btnXoaTatcaHDHangcho.Size = new System.Drawing.Size(228, 50);
            this.btnXoaTatcaHDHangcho.TabIndex = 118;
            this.btnXoaTatcaHDHangcho.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaTatcaHDHangcho.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoaTatcaHDHangcho.TextMarginLeft = 0;
            this.btnXoaTatcaHDHangcho.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoaTatcaHDHangcho.UseDefaultRadiusAndThickness = true;
            this.btnXoaTatcaHDHangcho.Click += new System.EventHandler(this.btnXoaTatcaHDHangcho_Click);
            // 
            // txtSotrang
            // 
            this.txtSotrang.AcceptsReturn = false;
            this.txtSotrang.AcceptsTab = false;
            this.txtSotrang.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.txtSotrang.AnimationSpeed = 200;
            this.txtSotrang.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSotrang.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSotrang.BackColor = System.Drawing.Color.Transparent;
            this.txtSotrang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSotrang.BackgroundImage")));
            this.txtSotrang.BorderColorActive = System.Drawing.SystemColors.Control;
            this.txtSotrang.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSotrang.BorderColorHover = System.Drawing.SystemColors.ButtonFace;
            this.txtSotrang.BorderColorIdle = System.Drawing.Color.Gray;
            this.txtSotrang.BorderRadius = 1;
            this.txtSotrang.BorderThickness = 1;
            this.txtSotrang.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSotrang.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSotrang.DefaultFont = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.txtSotrang.DefaultText = "1";
            this.txtSotrang.FillColor = System.Drawing.Color.Gainsboro;
            this.txtSotrang.HideSelection = true;
            this.txtSotrang.IconLeft = null;
            this.txtSotrang.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSotrang.IconPadding = 10;
            this.txtSotrang.IconRight = null;
            this.txtSotrang.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSotrang.Lines = new string[] {
        "1"};
            this.txtSotrang.Location = new System.Drawing.Point(353, 689);
            this.txtSotrang.MaxLength = 32767;
            this.txtSotrang.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSotrang.Modified = false;
            this.txtSotrang.Multiline = false;
            this.txtSotrang.Name = "txtSotrang";
            stateProperties5.BorderColor = System.Drawing.SystemColors.Control;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSotrang.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSotrang.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSotrang.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Gray;
            stateProperties8.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSotrang.OnIdleState = stateProperties8;
            this.txtSotrang.Padding = new System.Windows.Forms.Padding(3);
            this.txtSotrang.PasswordChar = '\0';
            this.txtSotrang.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSotrang.PlaceholderText = "";
            this.txtSotrang.ReadOnly = false;
            this.txtSotrang.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSotrang.SelectedText = "";
            this.txtSotrang.SelectionLength = 0;
            this.txtSotrang.SelectionStart = 1;
            this.txtSotrang.ShortcutsEnabled = true;
            this.txtSotrang.Size = new System.Drawing.Size(125, 49);
            this.txtSotrang.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSotrang.TabIndex = 117;
            this.txtSotrang.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtSotrang.TextMarginBottom = 0;
            this.txtSotrang.TextMarginLeft = 3;
            this.txtSotrang.TextMarginTop = 0;
            this.txtSotrang.TextPlaceholder = "";
            this.txtSotrang.UseSystemPasswordChar = false;
            this.txtSotrang.WordWrap = true;
            // 
            // btnLast
            // 
            this.btnLast.AllowAnimations = true;
            this.btnLast.AllowMouseEffects = true;
            this.btnLast.AllowToggling = false;
            this.btnLast.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnLast.AnimationSpeed = 200;
            this.btnLast.AutoGenerateColors = false;
            this.btnLast.AutoRoundBorders = false;
            this.btnLast.AutoSizeLeftIcon = true;
            this.btnLast.AutoSizeRightIcon = true;
            this.btnLast.BackColor = System.Drawing.Color.Transparent;
            this.btnLast.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnLast.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLast.BackgroundImage")));
            this.btnLast.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.ButtonText = "";
            this.btnLast.ButtonTextMarginLeft = 0;
            this.btnLast.ColorContrastOnClick = 45;
            this.btnLast.ColorContrastOnHover = 45;
            this.btnLast.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnLast.CustomizableEdges = borderEdges6;
            this.btnLast.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLast.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLast.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLast.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLast.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLast.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.btnLast.ForeColor = System.Drawing.Color.White;
            this.btnLast.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLast.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLast.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLast.IconMarginLeft = 11;
            this.btnLast.IconPadding = 2;
            this.btnLast.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLast.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLast.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLast.IconSize = 25;
            this.btnLast.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.IdleBorderRadius = 30;
            this.btnLast.IdleBorderThickness = 1;
            this.btnLast.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.IdleIconLeftImage = null;
            this.btnLast.IdleIconRightImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_end_24px;
            this.btnLast.IndicateFocus = false;
            this.btnLast.Location = new System.Drawing.Point(622, 692);
            this.btnLast.Name = "btnLast";
            this.btnLast.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLast.OnDisabledState.BorderRadius = 30;
            this.btnLast.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnDisabledState.BorderThickness = 1;
            this.btnLast.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLast.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLast.OnDisabledState.IconLeftImage = null;
            this.btnLast.OnDisabledState.IconRightImage = null;
            this.btnLast.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLast.onHoverState.BorderRadius = 30;
            this.btnLast.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.onHoverState.BorderThickness = 1;
            this.btnLast.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLast.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLast.onHoverState.IconLeftImage = null;
            this.btnLast.onHoverState.IconRightImage = null;
            this.btnLast.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.OnIdleState.BorderRadius = 30;
            this.btnLast.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnIdleState.BorderThickness = 1;
            this.btnLast.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLast.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLast.OnIdleState.IconLeftImage = null;
            this.btnLast.OnIdleState.IconRightImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_end_24px;
            this.btnLast.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLast.OnPressedState.BorderRadius = 30;
            this.btnLast.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLast.OnPressedState.BorderThickness = 1;
            this.btnLast.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLast.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLast.OnPressedState.IconLeftImage = null;
            this.btnLast.OnPressedState.IconRightImage = null;
            this.btnLast.Size = new System.Drawing.Size(118, 40);
            this.btnLast.TabIndex = 113;
            this.btnLast.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLast.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLast.TextMarginLeft = 0;
            this.btnLast.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLast.UseDefaultRadiusAndThickness = true;
            this.btnLast.Click += new System.EventHandler(this.btnLast_Click);
            // 
            // btnNext
            // 
            this.btnNext.AllowAnimations = true;
            this.btnNext.AllowMouseEffects = true;
            this.btnNext.AllowToggling = false;
            this.btnNext.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnNext.AnimationSpeed = 200;
            this.btnNext.AutoGenerateColors = false;
            this.btnNext.AutoRoundBorders = false;
            this.btnNext.AutoSizeLeftIcon = true;
            this.btnNext.AutoSizeRightIcon = true;
            this.btnNext.BackColor = System.Drawing.Color.Transparent;
            this.btnNext.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnNext.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNext.BackgroundImage")));
            this.btnNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.ButtonText = "";
            this.btnNext.ButtonTextMarginLeft = 0;
            this.btnNext.ColorContrastOnClick = 45;
            this.btnNext.ColorContrastOnHover = 45;
            this.btnNext.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnNext.CustomizableEdges = borderEdges7;
            this.btnNext.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNext.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNext.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnNext.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.btnNext.ForeColor = System.Drawing.Color.White;
            this.btnNext.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNext.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnNext.IconMarginLeft = 11;
            this.btnNext.IconPadding = 2;
            this.btnNext.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNext.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNext.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNext.IconSize = 25;
            this.btnNext.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.IdleBorderRadius = 30;
            this.btnNext.IdleBorderThickness = 1;
            this.btnNext.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.IdleIconLeftImage = null;
            this.btnNext.IdleIconRightImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_fast_forward_24px_1;
            this.btnNext.IndicateFocus = false;
            this.btnNext.Location = new System.Drawing.Point(487, 692);
            this.btnNext.Name = "btnNext";
            this.btnNext.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNext.OnDisabledState.BorderRadius = 30;
            this.btnNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnDisabledState.BorderThickness = 1;
            this.btnNext.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNext.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNext.OnDisabledState.IconLeftImage = null;
            this.btnNext.OnDisabledState.IconRightImage = null;
            this.btnNext.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.BorderRadius = 30;
            this.btnNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.onHoverState.BorderThickness = 1;
            this.btnNext.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnNext.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNext.onHoverState.IconLeftImage = null;
            this.btnNext.onHoverState.IconRightImage = null;
            this.btnNext.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.OnIdleState.BorderRadius = 30;
            this.btnNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnIdleState.BorderThickness = 1;
            this.btnNext.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnNext.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnIdleState.IconLeftImage = null;
            this.btnNext.OnIdleState.IconRightImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_fast_forward_24px_1;
            this.btnNext.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNext.OnPressedState.BorderRadius = 30;
            this.btnNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnNext.OnPressedState.BorderThickness = 1;
            this.btnNext.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnNext.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNext.OnPressedState.IconLeftImage = null;
            this.btnNext.OnPressedState.IconRightImage = null;
            this.btnNext.Size = new System.Drawing.Size(118, 40);
            this.btnNext.TabIndex = 114;
            this.btnNext.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnNext.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNext.TextMarginLeft = 0;
            this.btnNext.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnNext.UseDefaultRadiusAndThickness = true;
            this.btnNext.Click += new System.EventHandler(this.btnNext_Click);
            // 
            // btnFirst
            // 
            this.btnFirst.AllowAnimations = true;
            this.btnFirst.AllowMouseEffects = true;
            this.btnFirst.AllowToggling = false;
            this.btnFirst.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnFirst.AnimationSpeed = 200;
            this.btnFirst.AutoGenerateColors = false;
            this.btnFirst.AutoRoundBorders = false;
            this.btnFirst.AutoSizeLeftIcon = true;
            this.btnFirst.AutoSizeRightIcon = true;
            this.btnFirst.BackColor = System.Drawing.Color.Transparent;
            this.btnFirst.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnFirst.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFirst.BackgroundImage")));
            this.btnFirst.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.ButtonText = "";
            this.btnFirst.ButtonTextMarginLeft = 0;
            this.btnFirst.ColorContrastOnClick = 45;
            this.btnFirst.ColorContrastOnHover = 45;
            this.btnFirst.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnFirst.CustomizableEdges = borderEdges8;
            this.btnFirst.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFirst.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirst.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFirst.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFirst.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFirst.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.btnFirst.ForeColor = System.Drawing.Color.White;
            this.btnFirst.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFirst.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirst.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFirst.IconMarginLeft = 11;
            this.btnFirst.IconPadding = 2;
            this.btnFirst.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFirst.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirst.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFirst.IconSize = 25;
            this.btnFirst.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.IdleBorderRadius = 30;
            this.btnFirst.IdleBorderThickness = 1;
            this.btnFirst.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.IdleIconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_skip_to_start_24px;
            this.btnFirst.IdleIconRightImage = null;
            this.btnFirst.IndicateFocus = false;
            this.btnFirst.Location = new System.Drawing.Point(98, 692);
            this.btnFirst.Name = "btnFirst";
            this.btnFirst.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirst.OnDisabledState.BorderRadius = 30;
            this.btnFirst.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnDisabledState.BorderThickness = 1;
            this.btnFirst.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFirst.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFirst.OnDisabledState.IconLeftImage = null;
            this.btnFirst.OnDisabledState.IconRightImage = null;
            this.btnFirst.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFirst.onHoverState.BorderRadius = 30;
            this.btnFirst.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.onHoverState.BorderThickness = 1;
            this.btnFirst.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFirst.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFirst.onHoverState.IconLeftImage = null;
            this.btnFirst.onHoverState.IconRightImage = null;
            this.btnFirst.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.OnIdleState.BorderRadius = 30;
            this.btnFirst.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnIdleState.BorderThickness = 1;
            this.btnFirst.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnFirst.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFirst.OnIdleState.IconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_skip_to_start_24px;
            this.btnFirst.OnIdleState.IconRightImage = null;
            this.btnFirst.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFirst.OnPressedState.BorderRadius = 30;
            this.btnFirst.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFirst.OnPressedState.BorderThickness = 1;
            this.btnFirst.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFirst.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFirst.OnPressedState.IconLeftImage = null;
            this.btnFirst.OnPressedState.IconRightImage = null;
            this.btnFirst.Size = new System.Drawing.Size(117, 40);
            this.btnFirst.TabIndex = 115;
            this.btnFirst.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFirst.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFirst.TextMarginLeft = 0;
            this.btnFirst.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFirst.UseDefaultRadiusAndThickness = true;
            this.btnFirst.Click += new System.EventHandler(this.btnFirst_Click);
            // 
            // btnPrev
            // 
            this.btnPrev.AllowAnimations = true;
            this.btnPrev.AllowMouseEffects = true;
            this.btnPrev.AllowToggling = false;
            this.btnPrev.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.btnPrev.AnimationSpeed = 200;
            this.btnPrev.AutoGenerateColors = false;
            this.btnPrev.AutoRoundBorders = false;
            this.btnPrev.AutoSizeLeftIcon = true;
            this.btnPrev.AutoSizeRightIcon = true;
            this.btnPrev.BackColor = System.Drawing.Color.Transparent;
            this.btnPrev.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnPrev.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPrev.BackgroundImage")));
            this.btnPrev.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.ButtonText = "";
            this.btnPrev.ButtonTextMarginLeft = 0;
            this.btnPrev.ColorContrastOnClick = 45;
            this.btnPrev.ColorContrastOnHover = 45;
            this.btnPrev.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnPrev.CustomizableEdges = borderEdges9;
            this.btnPrev.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPrev.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrev.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrev.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrev.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPrev.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.btnPrev.ForeColor = System.Drawing.Color.White;
            this.btnPrev.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrev.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrev.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPrev.IconMarginLeft = 11;
            this.btnPrev.IconPadding = 2;
            this.btnPrev.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrev.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrev.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPrev.IconSize = 25;
            this.btnPrev.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.IdleBorderRadius = 30;
            this.btnPrev.IdleBorderThickness = 1;
            this.btnPrev.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.IdleIconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_rewind_24px;
            this.btnPrev.IdleIconRightImage = null;
            this.btnPrev.IndicateFocus = false;
            this.btnPrev.Location = new System.Drawing.Point(230, 692);
            this.btnPrev.Name = "btnPrev";
            this.btnPrev.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrev.OnDisabledState.BorderRadius = 30;
            this.btnPrev.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnDisabledState.BorderThickness = 1;
            this.btnPrev.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrev.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrev.OnDisabledState.IconLeftImage = null;
            this.btnPrev.OnDisabledState.IconRightImage = null;
            this.btnPrev.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPrev.onHoverState.BorderRadius = 30;
            this.btnPrev.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.onHoverState.BorderThickness = 1;
            this.btnPrev.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPrev.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPrev.onHoverState.IconLeftImage = null;
            this.btnPrev.onHoverState.IconRightImage = null;
            this.btnPrev.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.OnIdleState.BorderRadius = 30;
            this.btnPrev.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnIdleState.BorderThickness = 1;
            this.btnPrev.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPrev.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnPrev.OnIdleState.IconLeftImage = global::QuanLyCuaHangThoiTrangKD.Properties.Resources.icons8_rewind_24px;
            this.btnPrev.OnIdleState.IconRightImage = null;
            this.btnPrev.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPrev.OnPressedState.BorderRadius = 30;
            this.btnPrev.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrev.OnPressedState.BorderThickness = 1;
            this.btnPrev.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPrev.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPrev.OnPressedState.IconLeftImage = null;
            this.btnPrev.OnPressedState.IconRightImage = null;
            this.btnPrev.Size = new System.Drawing.Size(117, 40);
            this.btnPrev.TabIndex = 116;
            this.btnPrev.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrev.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPrev.TextMarginLeft = 0;
            this.btnPrev.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPrev.UseDefaultRadiusAndThickness = true;
            this.btnPrev.Click += new System.EventHandler(this.btnPrev_Click);
            // 
            // FormDanhsachHangchoHoadon
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Gainsboro;
            this.ClientSize = new System.Drawing.Size(1085, 767);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.bunifuShapes1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txtSDTKH);
            this.Controls.Add(this.grdDanhsachHDHangcho);
            this.Controls.Add(this.btnThanhtoanHDHangcho);
            this.Controls.Add(this.btnXoaHDHangcho);
            this.Controls.Add(this.btnTImkiemHDHangcho);
            this.Controls.Add(this.btnXoaTatcaHDHangcho);
            this.Controls.Add(this.txtSotrang);
            this.Controls.Add(this.btnLast);
            this.Controls.Add(this.btnNext);
            this.Controls.Add(this.btnFirst);
            this.Controls.Add(this.btnPrev);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximumSize = new System.Drawing.Size(1085, 767);
            this.MinimumSize = new System.Drawing.Size(1085, 767);
            this.Name = "FormDanhsachHangchoHoadon";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormDanhsachHangchoHoadon";
            ((System.ComponentModel.ISupportInitialize)(this.grdDanhsachHDHangcho)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView grdDanhsachHDHangcho;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtSotrang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLast;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNext;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFirst;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPrev;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaTatcaHDHangcho;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaHDHangcho;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThanhtoanHDHangcho;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes1;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtSDTKH;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDong;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTImkiemHDHangcho;
        private System.Windows.Forms.DataGridViewTextBoxColumn Mahd;
        private System.Windows.Forms.DataGridViewTextBoxColumn TenKH;
        private System.Windows.Forms.DataGridViewTextBoxColumn SDT;
    }
}