// <auto-generated />
namespace QuanLyCuaHangThoiTrangKD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KDSHOP_Migra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KDSHOP_Migra));
        
        string IMigrationMetadata.Id
        {
            get { return "202112250956561_KDSHOP_Migra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
